gsutil cp linkage_dag.py gs://us-east1-etl-05d83c6e-bucket/dags/
gsutil cp utils/clean_corpus.py gs://us-east1-etl-05d83c6e-bucket/dags/linkage_scripts/
gsutil cp utils/run_lid.py gs://us-east1-etl-05d83c6e-bucket/dags/linkage_scripts/
gsutil cp sql/arxiv_authors.sql gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/arxiv_metadata.sql gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/ds_authors.sql gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/ds_metadata.sql gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/mag_authors.sql gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/mag_metadata.sql gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/wos_authors.sql gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/wos_ids.sql gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/wos_abstracts.sql gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/wos_pubyears.sql gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/wos_titles.sql gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/wos_metadata.sql gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/cnki_year_doi_authors.sql gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/cnki_title.sql gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/cnki_abstract.sql gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/cnki_metadata.sql gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/union_metadata.sql gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/year_title_abstract.sql  gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/year_title_author.sql  gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/year_title_references.sql  gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/year_title_doi.sql  gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/year_abstract_author.sql  gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/year_abstract_references.sql  gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/year_abstract_doi.sql  gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/year_author_references.sql  gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/year_author_doi.sql  gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/year_references_doi.sql  gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/title_abstract_author.sql  gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/title_abstract_references.sql  gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/title_abstract_doi.sql  gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/title_author_references.sql  gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/title_author_doi.sql  gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/title_references_doi.sql  gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/abstract_author_references.sql  gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/abstract_author_doi.sql  gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/abstract_references_doi.sql  gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/author_references_doi.sql  gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/metadata_self_triple_match.sql  gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/all_match_pairs_with_um.sql  gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/simhash_input.sql gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/article_links_with_meta.sql gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/article_merged_meta.sql gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp sql/article_links_with_dataset.sql gs://us-east1-etl-05d83c6e-bucket/dags/sql/article_linkage/
gsutil cp schemas/metadata.json gs://airflow-data-exchange/article_linkage/schemas/
gsutil cp schemas/links_table.json gs://airflow-data-exchange/article_linkage/schemas/
gsutil cp create_merge_ids.py gs://airflow-data-exchange/article_linkage/vm_scripts/
gsutil cp utils/run_simhash.py gs://airflow-data-exchange/article_linkage/vm_scripts/
gsutil cp utils/article_linkage_lid_dataflow_requirements.txt gs://us-east1-etl-05d83c6e-bucket/dags/requirements/
gsutil cp article_linkage_text_clean_requirements.txt gs://us-east1-etl-05d83c6e-bucket/dags/requirements/
